monolith/models/mark.py
from monolith import db
from .timestamp_mixin import TimestampMixin


class Mark(TimestampMixin, db.Model):
    __tablename__ = "mark"
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), primary_key=True)
    authority_id = db.Column(
        db.Integer, db.ForeignKey("authority.id"), primary_key=True
    )

    authority = db.relationship("HealthAuthority", back_populates="marks")
    user = db.relationship("User", back_populates="marks")

    duration = db.Column(db.Integer, default=14)

monolith/controllers/restaurant.py
from monolith.models import Restaurant, RestaurantsPrecautions
from monolith.models.table import Table
from monolith import db


def add_new_restaurant(restaurant, prec_measures=None):
    q_rest = Restaurant.query.filter_by(
        lat=float(restaurant.lat),
        lon=float(restaurant.lon),
        operator_id=restaurant.operator_id,
    )
    if q_rest.first() is None:
        db.session.add(restaurant)
        db.session.commit()

        if prec_measures:
            for prec in prec_measures:
                new_restprec = RestaurantsPrecautions(
                    restaurant_id=restaurant.id, precautions_id=int(prec)
                )
                db.session.add(new_restprec)
                db.session.commit()

        return True
    else:
        return False


def check_restaurant_ownership(operator_id, restaurant_id):
    q = Restaurant.query.filter_by(id=restaurant_id, operator_id=operator_id)
    if q.first() is not None:
        return True
    else:
        return False


def add_new_table(table):
    q = Table.query.filter_by(name=table.name)
    if q.first() is None:
        db.session.add(table)
        db.session.commit()

        return True
    else:
        return False


def delete_table(table):
    q = Table.query.filter_by(id=table.id).first()
    if q is not None:
        db.session.delete(q)
        db.session.commit()

        return True
    else:
        return False


def check_table_existence(table):
    q = Table.query.filter_by(id=table.id).first()
    if q is not None:
        return True
    else:
        return False


def edit_table(table):
    table_to_edit = Table.query.filter_by(id=table.id).first()
    existing_table = Table.query.filter(
        Table.name == table.name,
        Table.id != table.id,
        Table.restaurant_id == table.restaurant_id,
    ).first()

    if existing_table is None:
        table_to_edit.name = table.name
        table_to_edit.seats = table.seats
        db.session.commit()
        return True
    else:
        return False

monolith/views/operators.py
from flask import Blueprint, redirect, render_template, request
from monolith import db
from monolith.models import Operator
from monolith.services.forms import OperatorForm

operators = Blueprint("operators", __name__)


@operators.route("/register/operator", methods=["GET", "POST"])
def create_operator():
    form = OperatorForm()
    if request.method == "POST":

        if form.validate_on_submit():
            operator = (
                db.session.query(Operator.id).filter_by(email=form.email.data).scalar()
            )
            if operator is not None:
                return redirect("/login/operator")
            else:
                new_operator = Operator(
                    firstname=form.firstname.data,
                    lastname=form.lastname.data,
                    email=form.email.data,
                    password=form.password.data,
                    dateofbirth=form.dateofbirth.data,
                    phone_number=form.phone_number.data,
                    fiscal_code=form.fiscal_code.data,
                )
                db.session.add(new_operator)
                db.session.commit()
                return redirect("/")

    return render_template("create_operator.html", form=form)

monolith/views/profile.py
from flask import Blueprint, render_template, session, redirect
from flask_login import login_required
from flask.helpers import flash

from monolith import db
from monolith.models import User, Operator
from monolith.services.auth import current_user
from monolith.services.forms import (
    ChangePasswordForm,
    ChangeAnagraphicForm,
    ChangeContactForm,
)

me = Blueprint("me", __name__)


@me.route("/me")
@login_required
def profile():
    if session["role"] == "authority":
        return redirect("/")
    elif session["role"] == "user":
        user = db.session.query(User).filter(User.id == current_user.id).first()
        return render_template("profile.html", user=user)
    elif session["role"] == "operator":
        user = db.session.query(Operator).filter(Operator.id == current_user.id).first()
        return render_template("profile.html", user=user)


@me.route("/me/change_password", methods=["GET", "POST"])
@login_required
def change_password():
    form = ChangePasswordForm()

    if form.validate_on_submit():
        if current_user.verify_password(form.old_password.data):
            current_user.password = form.new_password.data
            flash("Operation successful!")
        else:
            flash("You've typed the wrong password!")

    return render_template("change_profile.html", form=form)


@me.route("/me/change_anagraphic", methods=["GET", "POST"])
@login_required
def change_anagraphic():
    form = ChangeAnagraphicForm()

    if form.validate_on_submit():
        if current_user.verify_password(form.password.data):
            current_user.firstname = form.firstname.data
            current_user.lastname = form.lastname.data
            current_user.dateofbirth = form.dateofbirth.data
            current_user.fiscal_code = form.fiscal_code.data
            db.session.commit()
            flash("Operation successful!")
        else:
            flash("You've typed the wrong password!")

    return render_template("change_profile.html", form=form)


@me.route("/me/change_contacts", methods=["GET", "POST"])
@login_required
def change_contacts():
    form = ChangeContactForm()

    if form.validate_on_submit():
        if current_user.verify_password(form.password.data):
            current_user.email = form.email.data
            current_user.phone_number = form.phone.data
            db.session.commit()
            flash("Operation successful!")
        else:
            flash("You've typed the wrong password!")
    return render_template("change_profile.html", form=form)

monolith/views/restaurants.py
from flask.globals import session
from flask.helpers import flash
from flask import Blueprint, redirect, render_template, request, url_for, abort
from monolith import db
from monolith.models import (
    Restaurant,
    Precautions,
    RestaurantsPrecautions,
    Table,
    User,
    Booking,
    Mark,
    Operator,
)
from monolith.models.menu import Menu, Food, FoodCategory
from monolith.models.table import Table
from monolith.services.auth import (
    current_user,
    operator_required,
    user_required,
)
from flask_login import current_user, login_required
from monolith.services.forms import (
    CreateRestaurantForm,
    CreateTableForm,
    ReviewForm,
    CreateBookingDateHourForm,
    ConfirmBookingForm,
    ChooseReservationData,
)
from ..controllers import restaurant
from datetime import date, timedelta, datetime
from sqlalchemy import func
from flask_login import current_user
from monolith.services.background.tasks import send_email
from werkzeug.utils import secure_filename

import os
import imghdr
import logging

restaurants = Blueprint("restaurants", __name__)


logger = logging.getLogger("monolith")



@restaurants.route("/restaurants")
def _restaurants(message=""):
    session.pop("previous_search", "")

    if request.args.get("q"):
        query = request.args.get("q")
        session["previous_search"] = query
        results, total = Restaurant.search(query, 1, 20)
        allrestaurants = results.all()
        logger.info(f"Searching for {query}")
    else:            
        allrestaurants = db.session.query(Restaurant)

    restaurants = [res.__dict__ for res in allrestaurants]
    images_path_dict = {}
    for el in restaurants:
        # print(el)
        path = "./monolith/static/uploads/" + str(el["id"])
        photos_paths = os.listdir(path)
        # gets only the first one
        if photos_paths:
            el["path"] = os.path.basename(photos_paths[0])
    
    return render_template(
        "restaurants.html",
        message=message,
        restaurants=restaurants,
        paths=images_path_dict,
        base_url=request.base_url,
        operator_restaurants=False,
    )


@restaurants.route("/restaurants/mine")
@login_required
@operator_required
def operator_restaurants(message=""):
    operator_restaurants = db.session.query(Restaurant).filter_by(
        operator_id=current_user.id
    )
    return render_template(
        "restaurants.html",
        message=message,
        restaurants=operator_restaurants,
        role=session["role"],
        base_url=request.base_url,
        operator_restaurants=True,
    )


@restaurants.route("/restaurants/<restaurant_id>", methods=["GET", "POST"])
def restaurant_sheet(restaurant_id):
    q_restaurant = db.session.query(Restaurant).filter_by(
        id=int(restaurant_id)).first()

    if q_restaurant is None:
        abort(404)

    q_restaurant_precautions = (
        db.session.query(Precautions.name)
        .filter(
            Precautions.id == RestaurantsPrecautions.precautions_id,
            RestaurantsPrecautions.restaurant_id == int(restaurant_id),
        )
        .all()
    )

    precautions = []
    for prec in q_restaurant_precautions:
        precautions.append(prec.name)

    average_rating = round(q_restaurant.average_rating, 1)

    # REVIEWS
    # TODO sort them by the most recent, or are they already in that order
    # TODO show in the view the date of the review
    reviews = q_restaurant.reviews
    form = ReviewForm()
    if form.is_submitted():
        if current_user.is_anonymous:
            flash("To review the restaurant you need to login.")
            return redirect(url_for("auth.login"))
        if form.validate():
            if session["role"] != "user":
                flash("Only a logged user can review a restaurant.")
            else:
                # Check if the user already did a review
                if current_user.already_reviewed(q_restaurant):
                    flash("You already reviewed this restaraunt")
                else:
                    rating = form.rating.data
                    message = form.message.data
                    current_user.review(q_restaurant, rating, message)
                    db.session.commit()
                    return redirect("/restaurants/" + restaurant_id)

    path = "./monolith/static/uploads/" + str(restaurant_id)
    photos_paths = os.listdir(path)

    names = []
    for path in photos_paths:
        names.append(os.path.basename(path))

    return render_template(
        "restaurantsheet.html",
        id=q_restaurant.id,
        name=q_restaurant.name,
        lat=q_restaurant.lat,
        lon=q_restaurant.lon,
        phone=q_restaurant.phone,
        precautions=precautions,
        average_rating=average_rating,
        open=q_restaurant.opening_hours,
        close=q_restaurant.closing_hours,
        cuisine=q_restaurant.cuisine_type.value,
        menus=q_restaurant.menus,
        base_url=request.base_url,
        reviews=reviews,
        form=form,
        operator_id=q_restaurant.operator_id,
        file_names=names
    )


@restaurants.route("/restaurants/<restaurant_id>/booking", methods=["GET", "POST"])
@login_required
@user_required
def book_table_form(restaurant_id):
    if db.session.query(Mark).filter_by(user_id=current_user.id).first() is not None:
        flash("You are marked so you can't book a table")
        return redirect("/restaurants/" + str(restaurant_id))

    form = CreateBookingDateHourForm()
    max_table_seats = (
        db.session.query(func.max(Table.seats))
        .filter(Table.restaurant_id == restaurant_id)
        .first()[0]
    )  # Take max seats from tables of restaurant_ud
    time = []
    range_hour = (
        db.session.query(Restaurant.time_of_stay).filter_by(
            id=restaurant_id).first()[0]
    )
    opening_hour = int(
        db.session.query(Restaurant.opening_hours)
        .filter_by(id=restaurant_id)
        .first()[0]
        * 60
    )
    closing_hour = int(
        db.session.query(Restaurant.closing_hours)
        .filter_by(id=restaurant_id)
        .first()[0]
        * 60
    )
    if closing_hour < opening_hour:
        closing_hour = closing_hour + (24 * 60)
    for i in range(opening_hour, closing_hour, range_hour):
        time.append(
            str(timedelta(minutes=i))[:-3]
            + " - "
            + str(timedelta(minutes=i + range_hour))[:-3]
        )

    if request.method == "POST":
        if form.validate_on_submit():
            number_persons = int(request.form["number_persons"])
            booking_hour_start = request.form["booking_hour"].split(" - ")[0]
            booking_hour_end = request.form["booking_hour"].split(" - ")[1]
            booking_date = request.form["booking_date"]
            booking_date_start = datetime.strptime(
                booking_date + " " + booking_hour_start, "%Y-%m-%d %H:%M"
            )
            booking_date_end = datetime.strptime(
                booking_date + " " + booking_hour_end, "%Y-%m-%d %H:%M"
            )

            restaurant = (
                db.session.query(Restaurant)
                .filter(Restaurant.id == restaurant_id)
                .first()
            )
            table = restaurant.get_free_table(
                number_persons, booking_date_start)

            if table is None:
                flash(
                    "No tables avaible for "
                    + str(number_persons)
                    + " people for this date and time"
                )
            else:
                booking_number = db.session.query(
                    func.max(Booking.booking_number)
                ).first()[0]
                print(booking_number)
                if booking_number is None:
                    booking_number = 1
                else:
                    booking_number += 1

                confirmed_bookign = True if number_persons == 1 else False
                db.session.add(
                    Booking(
                        user_id=current_user.id,
                        table_id=table,
                        booking_number=booking_number,
                        start_booking=booking_date_start,
                        end_booking=booking_date_end,
                        confirmed_booking=confirmed_bookign,
                    )
                )
                db.session.commit()

                old_booking_number = booking_number

                if confirmed_bookign:
                    flash("Booking confirmed", category="success")
                    return redirect("/restaurants")
                else:
                    session["booking_number"] = old_booking_number
                    session["number_persons"] = number_persons
                    return redirect(
                        url_for(".confirm_booking",
                                restaurant_id=restaurant_id)
                    )
        else:
            flash("Are you really able to go back to the past?")

    return render_template(
        "book_table.html", form=form, max_table_seats=max_table_seats, hours_list=time
    )


@restaurants.route(
    "/restaurants/<restaurant_id>/booking/confirm", methods=["GET", "POST"]
)
@login_required
@user_required
def confirm_booking(restaurant_id):
    booking_number = session["booking_number"]
    number_persons = session["number_persons"]
    form = ConfirmBookingForm(number_persons - 1)
    error = False

    if form.validate_on_submit():
        booking = (
            db.session.query(Booking).filter_by(
                booking_number=booking_number).first()
        )

        for i, field in enumerate(form.people):
            user = (
                db.session.query(User)
                .filter_by(fiscal_code=field.fiscal_code.data)
                .first()
            )
            if user is None:
                if (
                    db.session.query(User).filter_by(

monolith/views/users.py
from flask import Blueprint, redirect, render_template, request
from monolith import db
from monolith.models import User
from monolith.services.forms import UserForm
from monolith.services.auth import authority_required

users = Blueprint("users", __name__)


@users.route("/users")
@authority_required
def _users():
    users = db.session.query(User)
    return render_template("users.html", users=users)


@users.route("/register/user", methods=["GET", "POST"])
def create_user():
    form = UserForm()
    if request.method == "POST":
        if form.validate_on_submit():
            user = db.session.query(User.id).filter_by(email=form.email.data).scalar()
            if user is not None:
                return redirect("/login/user")
            else:
                new_user = User(
                    firstname=form.firstname.data,
                    lastname=form.lastname.data,
                    email=form.email.data,
                    password=form.password.data,
                    dateofbirth=form.dateofbirth.data,
                    phone_number=form.phone_number.data,
                    fiscal_code=form.fiscal_code.data,
                )

                db.session.add(new_user)
                db.session.commit()
                return redirect("/")

    return render_template("create_user.html", form=form)

monolith/templates/_formhelpers.html
{% macro render_field(field) %}
{{ field.csrf_token }}
<dt>{{ field.label }}
    <dd>{{ field(**kwargs)|safe }}
        {% if field.errors %}
            <ul class=errors>
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </dd>
</dt>
{% endmacro %}

monolith/templates/base.html
<!DOCTYPE html>
<html>

<head>
    {% block head %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} - GoOutSafe</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"
        integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ=="
        crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <!-- jQuery 1.8 or later, 33 KB -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <!-- Fotorama from CDNJS, 19 KB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js"></script>
    {% endblock %}
    <style>
        .fotorama__wrap {
            margin: 0 auto;
        }
    </style>
</head>

<body style="margin-bottom:50px">
    <header>
        <div class="ui centered grid">
            <div class="row"></div>
            <div class="row">
                <div class="ui container"><a href="/" title="Home Page"><img width=10%
                            src="{{ url_for('static', filename='assets/logo.png') }}" alt="Go Out Safe"></a></div>
            </div>
            <div class="row">
                <div class="ui menu center primary">
                    <a href="/" class="item" title="Home Page">Home</a>
                    <form method="GET" action="{{ url_for('restaurants._restaurants') }}">
                        <div class="item">
                            <div class="ui inverted icon input">
                                <i class="search icon"></i>
                                {% if session.get('previous_search') %}
                                <input id="search" name="q" type="prompt" placeholder="Search"
                                    value="{{ session.get('previous_search') }}">
                                {% else %}
                                <input id="search" name="q" type="prompt" placeholder="Search">
                                {% endif %}
                            </div>
                        </div>
                    </form>
                    <div class="right menu">
                        {% if not (current_user.is_authenticated and current_user.is_active) %}
                        <a href="/login/user" class="item">Login</a>
                        {% else %}
                        {% if session["role"] == "user" or "operator" %}
                        <a href="/me" class="item">{{ session["name"] }}</a>
                        {% else %}
                        {{ session["name"] }}
                        {% endif %}
                        {% if session["role"] == 'user' %}
                        <a href="/bookings" class="item">Booking</a>
                        {% endif %}
                        {% if session["role"] == 'authority' %}
                        <a href="/marks/new" class="item">Mark<div class="ui red horizontal empty circular label"></div>
                        </a>
                        <a href="/trace" class="item">Trace<div class="ui red horizontal empty circular label"></div>
                        </a>
                        {% endif %}
                        <a href="/logout" class="item">Logout</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        </div>
        </div>
    </header>
    <main>
        <section style="margin-top:30px; margin-bottom:0px" class="ui text container">
            <!--ADD css to close the message-->
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            {% if category == "success" %}
            <div id="popup" class="ui success message close transition" onclick="closePopup()">
                <i class=" close icon"></i>
                <div class="header">
                    Success!
                </div>
                <ul class="list">
                    <li>{{ message }}</li>
                </ul>
            </div>
            {% elif category == "info" %}
            <div id="popup" class="ui info message close transition" onclick="closePopup()">
                <i class=" close icon"></i>
                <div class="header">
                    Info
                </div>
                <ul class="list">
                    <li>{{ message }}</li>
                </ul>
            </div>
            {% else %}
            <div id="popup" class="ui error message close transition" onclick="closePopup()">
                <i class="close icon"></i>
                <div class="header">
                    There were some errors with your submission
                </div>
                <ul class="list">
                    <li>{{ message }}</li>
                </ul>
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
            {% endwith %}
        </section>
        {% block before_main %}{% endblock %}
        <section class="ui text container">
            {% block main %}{% endblock %}
        </section>
        <div class="ui divider hidden"></div>
    </main>
    <!--<footer class="ui inverted vertical footer segment">
        <div class="ui container">
            Copyright 2020
        </div>
    </footer>-->
</body>

<script>
    function closePopup() {
        let messagePopup = document.getElementById("popup");
        messagePopup.style.display = "none";
    }
</script>

</html>

monolith/templates/book_table.html
{% extends "base.html" %}
{% block title %}Index{% endblock %}

{% block main %}
<h1>Book table</h1>
<form method="POST" action="">
   <dl>
        <h3 class="ui header">
            <i class="calendar outline icon"></i>
            <div class="content">
                {{ form.booking_date.label }}
            </div>
        </h3>
        <dd>{{ form.booking_date }}</dd>

        <h3 class="ui header">
            <i class="clock outline icon"></i>
            <div class="content">
                Booking hour
            </div>
        </h3>
        <dd>
            <select name="booking_hour">
                {% for i in hours_list %}
                    <option value="{{ i }}">{{ i }}</option>
                {% endfor %}
            </select>
        </dd>

        <h3 class="ui header">
            <i class="users icon"></i>
            <div class="content">
                People number
            </div>
        </h3>
        <dd>
            <select name="number_persons">
                {% for i in range(1,max_table_seats+1) %}
                    <option value="{{ i }}">{{ i }}</option>
                {% endfor %}
            </select>
        </dd>
    </dl>
    <input type=submit value="Submit" class="ui button primary">
</form>
{% endblock %}

monolith/templates/change_profile.html
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} - GoOutSafe</title>
    {% block head %}{% endblock %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='styles/semantic.min.css') }}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <!--<link rel="stylesheet" href="https://igoradamenko.github.io/awsm.css/css/awsm_theme_mischka.css">-->
    <!--<link rel="stylesheet" href="https://unpkg.com/mvp.css">-->
    <!--<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/picnic">-->
    <!--<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">-->

</head>

{% block main %}
<div class="ui container">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul class=flashes>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
    <form action="" method="POST" class="ui form">
        {{ form.hidden_tag() }}
        {% for field in form.display %}
        <div class="field">
            <label>{{ form[field].label }}</label>
            {{ form[field]() }}
        </div>
        {% if form[field].errors %}
        {% for e in form[field].errors %}
        <p class="help-block">{{ e }}</p>
        {% endfor %}
        {% endif %}
        {% endfor %}
        <p>
            <input type=submit value="Submit" class="ui button primary">
    </form>
</div>
{% endblock %}

monolith/templates/create_operator.html
{% extends "base.html" %}
{% block title %}Index{% endblock %}

{% block main %}
<form action="" method="POST" class="ui form">
    {{ form.hidden_tag() }}
    {% for field in form.display %}
    <div class="field">
        <label>{{ form[field].label }}</label>
        {{ form[field]() }}
    </div>
    {% if form[field].errors %}
    {% for e in form[field].errors %}
    <p class="help-block">{{ e }}</p>
    {% endfor %}
    {% endif %}
    {% endfor %}
    <p>
        <input type=submit value="Submit" class="ui button primary">
</form>
{% endblock %}

monolith/templates/create_user.html
{% extends "base.html" %}
{% block title %}Index{% endblock %}

{% block main %}
<form action="" method="POST" class="ui form">
    {{ form.hidden_tag() }}
    {% for field in form.display %}
    <div class="field">
        <label>{{ form[field].label }}</label>
        {{ form[field]() }}
    </div>
    {% if form[field].errors %}
    {% for e in form[field].errors %}
    <p class="help-block">{{ e }}</p>
    {% endfor %}
    {% endif %}
    {% endfor %}
    <p>
        <input type=submit value="Submit" class="ui button primary">
</form>
{% endblock %}

monolith/templates/login.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock %}

{% block main %}
<h3>{{ title }}</h3>


<form action="" method="POST" class="ui form">
    {{ form.hidden_tag() }}
    {% for field in form.display %}
    <div class="field">
        <label>{{ form[field].label }}</label>
        {{ form[field]() }}
    </div>
    {% if form[field].errors %}
    {% for e in form[field].errors %}
    <p class="help-block">{{ e }}</p>
    {% endfor %}
    {% endif %}
    {% endfor %}
    <p>
        <input type=submit value="Submit" class="ui button primary">
</form>

<!--TODO only show the links that are needed. If am on /login hide the first one-->
{% if title != "User Login" %}
<h5><a href="/login/user">Login as an User</a></h5>
{% endif %}
{% if title != "Operator Login" %}
<h5><a href="/login/operator">Login as an Operator</a></h5>
{% endif %}
{% if title != "Authority Login" %}
<h5><a href="/login/authority">Login as an Health Authority</a></h5>
{% endif %}

{% if title == "User Login" %}
<h5><a href="/register/user">User Sign Up</a></h5>
{% elif title == "Operator Login" %}
<h5><a href="/register/operator">Operator Sign Up</a></h5>
{% elif title == "Authority Login" %}
<h5><a href="/register/authority">Authority Sign Up</a></h5>
{% endif %}

{% endblock %}

monolith/templates/mark.html
{% extends "base.html" %}
{% block title %}Mark user{% endblock %}

{% block main %}

<section>
    <h2 class="ui header">Mark by using an identifier</h2>
    <form action="" method="POST" class="ui form">
        {{ form.hidden_tag() }}
        {% for field in form.display %}
        <div class="field">
            <label>{{ form[field].label }}</label>
            {{ form[field]() }}
        </div>
        {% if form[field].errors %}
        {% for e in form[field].errors %}
        <p class="help-block">{{ e }}</p>
        {% endfor %}
        {% endif %}
        {% endfor %}
        <p>
            <input type=submit value="Mark" class="ui button primary">
    </form>
</section>

{% endblock %}

monolith/templates/operators.html
{% extends "base.html" %}
{% block title %}Index{% endblock %}

{% block main %}
    <h1>User List</h1>
    <ul>
        {% for operator in operators: %}
            <li>
                {{ operator.firstname }} {{ operator.lastname }}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

monolith/templates/profile.html
{% extends "base.html" %}
{% block title %}Your Profile{% endblock %}

{% block main %}
<h2 class="ui dividing header">Profile information</h2>
<p>Welcome to your profile page, {{ session["name"] }}! Below you can check and modify your information.</p>
<div class="row ui list">
    <div class="item">First Name: {{ user.firstname }}</div>
    <div class="item">Last Name: {{ user.lastname }}</div>
    {% if session["role"] == user %}
    <div class="item">Phone Number: {{user.phone_number}}</div>
    {% endif %}
    <div class="item">Fiscal Code: {{user.fiscal_code}}</div>
    <div class="item">Email: {{user.email}}</div>
</div>

<div class="row">
    <div class="ui dividing header">Modify your information</div>
    <h3 class="row">Change password</h3>
    <iframe id="password_iframe" src="{{ url_for('me.change_password') }} " width="400" height="300"></iframe>
    <h3 class="row">Change anagraphic information</h3>
    <iframe id="anagraphic_iframe" src="{{ url_for('me.change_anagraphic') }} " width="400" height="300"></iframe>
    <h3 class="row">Change your contact information</h3>
    <iframe id="contacts_iframe" src="{{ url_for('me.change_contacts') }} " width="400" height="300"></iframe>

</div>
</div>

{% endblock %}